url: https://y7kim.github.io

baseurl: /tpe-sucre/

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]


# Site settings
title: Le sucre
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Yannis Scala
  pic: yannis
  position: Lycéen en première S à Champlain
  social:
    - title: facebook
      url: https://www.facebook.com/yannis.scala
    - title: google-plus
      url: https://plus.google.com/112606112660395660595

- name: Theo Pasquali
  pic: 2
  position: Lycéen en première S à Champlain
  social:
    - title: facebook
      url: https://www.facebook.com/theo94lqb

- name: Hugo Leduc
  pic: 3
  position: Lycéen en première S à Champlain
  social:
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/yannisscala/tpe-sucre

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
